# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from socket import *

HOST = "192.168.137.46"
PORT = 9999
ADDRESS = (HOST, PORT)
BUF_SIZE = 1024

s = socket()
s.connect(ADDRESS)


def start():
    print('listen for connection...')
    while True:
        print('got connection from', HOST)
        print('-------------------------')
        s.send('Thank you for connecting'.encode())
        data = s.recv(1024).decode()  # receive response

        print('Received from server: ' + data)
        break


def up():
    while True:
        s.send('UP'.encode())
        print("Up request sent")
        break


def down():
    while True:
        s.send('DOWN'.encode())
        print("Down request sent")
        break


def left():
    while True:
        s.send('LEFT'.encode())
        print("Left request sent")
        break


def right():
    while True:
        s.send('RIGHT'.encode())
        print("Right request sent")
        break


def station_1():
    while True:
        s.send('1'.encode())
        print("Station 1 request sent")
        break


def station_2():
    while True:
        s.send('2'.encode())
        print("Station 2 request sent")
        break


def station_3():
    while True:
        s.send('3'.encode())
        print("Station 3 request sent")
        break


def station_4():
    while True:
        s.send('4'.encode())
        print("Station 4 request sent")
        break


def station_5():
    while True:
        s.send('5'.encode())
        print("Station 5 request sent")
        break


def station_6():
    while True:
        s.send('6'.encode())
        print("Station 6 request sent")
        break


def close():
    s.send('Closed'.encode())
    s.close()


class Ui_RMAControl(object):
    def setupUi(self, RMAControl):
        RMAControl.setObjectName("RMAControl")
        RMAControl.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(RMAControl)
        self.centralwidget.setObjectName("centralwidget")
        self.Up = QtWidgets.QPushButton(self.centralwidget)
        self.Up.setGeometry(QtCore.QRect(280, 150, 75, 23))
        self.Up.setObjectName("Up")
        self.Up.clicked.connect(up)
        self.Left = QtWidgets.QPushButton(self.centralwidget)
        self.Left.setGeometry(QtCore.QRect(130, 220, 71, 23))
        self.Left.setObjectName("Left")
        self.Left.clicked.connect(left)
        self.Down = QtWidgets.QPushButton(self.centralwidget)
        self.Down.setGeometry(QtCore.QRect(280, 280, 75, 23))
        self.Down.setObjectName("Down")
        self.Down.clicked.connect(down)
        self.Right = QtWidgets.QPushButton(self.centralwidget)
        self.Right.setGeometry(QtCore.QRect(420, 220, 75, 23))
        self.Right.setObjectName("Right")
        self.Right.clicked.connect(right)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 50, 131, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.Start = QtWidgets.QPushButton(self.centralwidget)
        self.Start.setGeometry(QtCore.QRect(600, 120, 75, 23))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("C:/Users/CYBORG/Downloads/power.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Start.setIcon(icon)
        self.Start.setObjectName("Start")
        self.Start.clicked.connect(start)
        self.Stop = QtWidgets.QPushButton(self.centralwidget)
        self.Stop.setGeometry(QtCore.QRect(600, 340, 75, 23))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("C:/Users/CYBORG/Downloads/stop-sign.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.Stop.setIcon(icon1)
        self.Stop.setObjectName("Stop")
        self.Stop.clicked.connect(close)
        self.station1 = QtWidgets.QPushButton(self.centralwidget)
        self.station1.setGeometry(QtCore.QRect(80, 440, 75, 23))
        self.station1.setObjectName("station1")
        self.station1.clicked.connect(station_1)
        self.station2 = QtWidgets.QPushButton(self.centralwidget)
        self.station2.setGeometry(QtCore.QRect(170, 440, 75, 23))
        self.station2.setObjectName("station2")
        self.station2.clicked.connect(station_2)
        self.station3 = QtWidgets.QPushButton(self.centralwidget)
        self.station3.setGeometry(QtCore.QRect(260, 440, 75, 23))
        self.station3.setObjectName("station3")
        self.station3.clicked.connect(station_3)
        self.station4 = QtWidgets.QPushButton(self.centralwidget)
        self.station4.setGeometry(QtCore.QRect(350, 440, 75, 23))
        self.station4.setObjectName("station4")
        self.station4.clicked.connect(station_4)
        self.station5 = QtWidgets.QPushButton(self.centralwidget)
        self.station5.setGeometry(QtCore.QRect(440, 440, 75, 23))
        self.station5.setObjectName("station5")
        self.station5.clicked.connect(station_5)
        self.station6 = QtWidgets.QPushButton(self.centralwidget)
        self.station6.setGeometry(QtCore.QRect(530, 440, 75, 23))
        self.station6.setObjectName("station6")
        self.station6.clicked.connect(station_6)
        RMAControl.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(RMAControl)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        RMAControl.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(RMAControl)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        RMAControl.setStatusBar(self.statusbar)

        self.retranslateUi(RMAControl)
        QtCore.QMetaObject.connectSlotsByName(RMAControl)

    def retranslateUi(self, RMAControl):
        _translate = QtCore.QCoreApplication.translate
        RMAControl.setWindowTitle(_translate("RMAControl", "RMA Control"))
        self.Up.setText(_translate("RMAControl", "Up"))
        self.Left.setText(_translate("RMAControl", "Left"))
        self.Down.setText(_translate("RMAControl", "Down"))
        self.Right.setText(_translate("RMAControl", "Right"))
        self.label.setText(_translate("RMAControl", "Control Direction"))
        self.Start.setText(_translate("RMAControl", "Start"))
        self.Stop.setText(_translate("RMAControl", "Stop"))
        self.station1.setText(_translate("RMAControl", "1"))
        self.station2.setText(_translate("RMAControl", "2"))
        self.station3.setText(_translate("RMAControl", "3"))
        self.station4.setText(_translate("RMAControl", "4"))
        self.station5.setText(_translate("RMAControl", "5"))
        self.station6.setText(_translate("RMAControl", "6"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RMAControl = QtWidgets.QMainWindow()
    ui = Ui_RMAControl()
    ui.setupUi(RMAControl)
    RMAControl.show()
    sys.exit(app.exec_())
